#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScfMobileApp.Android.Resource", IsApplication=true)]

namespace ScfMobileApp.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int SCF_Background_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SCF_Background_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int SCF_Logo_Android_drawable = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btnAbortConnect = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int btnConnect = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int btnOrderDrink = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int drinkListView = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int lblConnectStatus = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int progressBar1 = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int tbxResponse = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int tbxServiceUrl = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int textItem = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int txtLastOrder = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int txtOrderResponse = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DrinkDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DrinkList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewDataItems = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AbortConnect = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Connect = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Connecting = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int NotConnected = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int ServiceUrl = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
